version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    ports:
      - "5000"
    stdin_open: true
    tty: true

volumes:
  db:
